### ISSUE TITLE
Warning logs in Editor

### ISSUE THREAD

**Issue by SamathyTheManathy** [DarkRiftNetworking/DarkRift#103]
Unnecessary warnings in Editor, mostly default value warnings.

![image](https://user-images.githubusercontent.com/49008088/94884136-f324df80-04af-11eb-9634-e24391c3d6e8.png)

Most of these warnings can be avoided by declaring the variable null, for example:

    [SerializeField]
    [Tooltip("The transform to place new messages in.")]
    Transform chatWindow = null;

Unity Version 2019.4.11f1
DarkRift Version: 2.7.0 Free

**Comment by JamJar00** [comment]
Hi,

Sorry it's taken so long to look into this and reply!

I don' see these errors using 2019.1 or 2020.2, do you have any additional settings enabled?

**Comment by JamJar00** [comment]
Managed to reproduce in the end! Fixed in the next version!
