### ISSUE TITLE
Bug: Host="localhost" doesn't function as expected in DarkRift.Client.Unity.UnityClient

### ISSUE THREAD

**Issue by aaronrmm** [DarkRiftNetworking/DarkRift#105]
### Quick Description
The host field of the Client component must be changed from "localhost" to "127.0.0.1" to connect to a local Darkrift2 server.

### Explanation
The tutorial documentation and the default value for DarkRift.Client.Unity.UnityClient Host field is "localhost". However, when the server is running on its default "0.0.0.0:4296"
and leads to the Unity error ```SocketException: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.```

#### Environment: 
Windows 10 
Unity Version: 2020.2.3f1.3936 Personal, Revision: 2020.2/staging 8ff31bc5bf5b

#### To reproduce,
Access DarkRift Networking 2 from the new AssetStore webpage and click Open in Unity. Import to your project from the Package Manager. Create an empty object and add the Client script component to it, leaving the defaults as they are. Unzip the server and double click DarkRift.Server.Console.exe. Then start your game inside Unity editor with the play button.

**Comment by JamJar00** [comment]
Hmm, that's not great.

I guess this is because the latest DR supports resolving an address via DNS and `localhost` _could_ be a valid domain name!

Good find!

**Comment by JamJar00** [comment]
Should be fixed in the next version

**Comment by attolee** [comment]
Still be found in darkrift pro.

**Comment by JamJar00** [comment]
@attolee this is being tracked in #120 now! Please add any information you might think useful there!
