### ISSUE TITLE
Metrics can't be read by Prometheus if DarkRift is running on certain locales

### ISSUE THREAD

**Issue by Shii2** [DarkRiftNetworking/DarkRift#106]
### Quick Description
Prometheus can't read DarkRift metrics data when DarkRift is running on machine with Russian locale

### Explanation
Getting error in Prometheus: `strconv.ParseFloat: parsing "0,0011075": invalid syntax`
I checked full metrics log and found line `darkrift_client_manager_client_connected_event_time_sum 0,0011075 1615031988315`
Apparently DarkRift outputting numbers in regional format selected in Windows and Prometheus only accepting invariant culture formats.
Probably fix would be applying CultureInfo.InvariantCulture to all numbers output metrics by DarkRift so output numbers will always contain dots instead of commas.

**Comment by JamJar00** [comment]
Good find with this one!

Should be fixed in the next version
