### ISSUE TITLE
Metrics not updating user count on client disconnection

### ISSUE THREAD

**Issue by Shii2** [DarkRiftNetworking/DarkRift#107]
### Quick Description
Using prometheus for getting metrics and darkrift not updating user count on client disconnection.

### Explanation
I fixed this by adding extra metrics update to the end of FinaliseClientDisconnect method in ClientManager.cs and it seems to be working now.

**Comment by JamJar00** [comment]
Ugh! Should've tested that scenario!

Fixed in the next version, and a system test added for the future!
