### ISSUE TITLE
Upgrade Dotnet Core Version

### ISSUE THREAD

**Issue by martindevans** [DarkRiftNetworking/DarkRift#113]
### Quick Description
Currently the standalone server only supports dotnet `core 2.0`, upgrade to dotnet `core 5.0` or `core 3.0`.

### Explanation
Dotnet core 2.0 is old enough that it doesn't support the latest netstandard (2.1), this means that server plugins cannot use any of [these things](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.1.md).

There are two options ([reference](https://en.wikipedia.org/wiki/.NET_Core)):
 - Core 3.0 is an LTS version with support until December 3, 2022. It supports netstandard 2.1 (the latest)
 - Core 5.0 is the latest version with support until "3 months after Core 6.0 release" (likely to be the end of this year, so support until early 2022). This gives it a smaller support window than 3.0, but better performance (I got a ~20% boost to some of my benchmarks just by switching from 3 to 5).

#### For Feature Requests
- Upgrade to core 3 or 5
- More supported libraries (netstandard 2.1) and better performance.

**Comment by JamJar00** [comment]
Hi Martin,

DR 2.10.0 now comes with NET 3.1 and .NET 5 builds 🎉
