### ISSUE TITLE
Server "help -L" does not list commands

### ISSUE THREAD

**Issue by Bamboy** [DarkRiftNetworking/DarkRift#119]
![724a2e747d3c1b33c73a808c637b9de4-png](https://user-images.githubusercontent.com/3387750/119902415-092e5700-befc-11eb-8dbb-78e627267154.jpg)

"help -L" interprets "-L" as if it is a command, instead of listing all available commands.

I personally would have the "help" command, when entered with no args, list all available commands. (including help itself, which could then specify you can enter "help [command]"). It makes more sense from an ease-of-use standpoint, and for those less technically inclined.

**Comment by JamJar00** [comment]
Fixed in next version! Good spot!
