### ISSUE TITLE
Write Serialization Issue 

### ISSUE THREAD

**Issue by martingg88** [DarkRiftNetworking/DarkRift#122]
i managed to integrated "DarkRift2-WebSocketListener" in DarkRift ecosystem and it work fine. I tried to use javascript WebSocket API that manage to connect to DarkRift server but for there is an issue  on sending/receiving message on javascript side as i receive most  about funny characters on javascript side. can I know is it the encoding issue? if yes, what is the default encoding used in DarkRift?

beside that, i tried the another way by turning the Instance/Object/Property/field into json string ,  DarkRift write Serialize the json string and then send it out to Javascript side. but i facing the BOM  Character/Byte (shown below) added in at beginning fo json string at javascript side. how to prevent any BOM prepending when doing   DarkRift write Serialization.

�{"test": 1}

**Comment by JamJar00** [comment]
Hi martingg88,

I think you posted a similar question in Discord, so I'll just summarise my response here.

DarkRift currently uses a proprietary protocol on top of websockets (or whatever other listener is in use), so the prepended characters are part of DarkRift's protocol. At some point I'd like to support custom protocols to open up integration with other applications but I don't think that will be anytime soon.

Closing this, you should still be able to comment if you need though.

Jamie
