### ISSUE TITLE
Turkish ISP deletes empty UDP Packages

### ISSUE THREAD

**Issue by caglarenes** [DarkRiftNetworking/DarkRift#130]
### Quick Description
Turkish ISP Turkcell Superonline ignores and deletes empty UDP messages. So, BiChannelListener can't connect successfully with Turkcell Superonline clients.

### Explanation
DarkRift.Server.BiChannelListenerBase.cs sends a one-byte UDP package that is full with zeros (line 281) for the last handshaking step but this package never reaches the client. On the client-side, the user waits for this package with ..Receive() method (DarkRift.Client.BichannelClientConnection.cs Line 158) But the last message never comes.

The real problem is Turkcell Superonline deletes one byte of empty UDP messages. TCP connection, token sending, UDP connection, and token receiving steps are successful. Only last handshaking part was unsuccessful because of a meaningless UDP message.

Changing DarkRift.Server.BiChannelListenerBase.cs like this solves our issue:

```
277
                MessageBuffer helloBuffer = MessageBuffer.Create(5);
                helloBuffer.Count = 5;
                helloBuffer.Buffer[0] = 7;
                helloBuffer.Buffer[1] = 16; 
                helloBuffer.Buffer[2] = 154; 
                helloBuffer.Buffer[3] = 210; 
                helloBuffer.Buffer[4] = 54;                           // Layout: 0 - Version
                connection.SendMessageUnreliable(helloBuffer);
281
```

Can we change the last message to a more meaningful one?

**Comment by 4real** [comment]
Should be solved in new version/master.
