### ISSUE TITLE
TCP Header Contains Corrupted Value

### ISSUE THREAD

**Issue by JamJar00** [DarkRiftNetworking/DarkRift#14]
### Quick Description
As noted by Mogull on Discord.

Sending rapid messages to the server is causing the TCP header to contain corrupt length values and hence the backing array for the message cannot be created.

### Explaination
The lines
```C#
int count = BigEndianHelper.ReadInt32(e.Buffer, 0);
e.SetBuffer(new byte[count], 0, count);
```
Are causing an exception ("Array dimensions exceeded supported range") as count is being read as a negative number.

This is after sending a large number of calls per second to the server.

#### Conditions to Reproduce
Console Server, version 2.0.1 or lower.

**Comment by mogull** [comment]
Using wireshark, no badly formed packet were sent to the server so it might not be a client side problem.

While debugging, when the error happened ` e.Buffer` showed the message's payload (or a part of)  rather than the header indicating the payload's size.

**Comment by JamJar00** [comment]
Hey mogull,

I'm trying to reproduce this now, can you give me an idea of how long you normally have/had to wait before it crashes?

Jamie

**Comment by JamJar00** [comment]
Closing as I couldn't reproduce it and haven't heard anything similar since! If you think it's still an issue feel free to repoen 🙂
