### ISSUE TITLE
Two race conditions are uncaught.

### ISSUE THREAD

**Issue by RobbieLePommie** [DarkRiftNetworking/DarkRift#146]
**Situation 1**: A client firing messages too quick will have some messages dropped as the server listeners are not ready.

Sequence of events:
 - Client Initiates connection(s), and waits based on Mutex. Receipt of Client.ID will clear the Mutux and allow client to proceed.
 - UDP Connection is established; Sever sends Client.ID
 - Server initiates listeners.
 - Race Condition: Client connection is complete and may send messages before Server has initiated the listeners. Experienced when server under load.

Solution: Notify client of their Client.ID once connection is listening; this ends the mutex on client side that allows post-connection events to run.

Notes:
 - this was already noted in a "TODO" (have removed that TODO);
 - tested in our test setup; 1000 clients could fully connect in 40-50 seconds [approx; we only log each 10 seconds] and send additional negotiation (security) messages immediately after connect - with zero failure/retry.

**Situation 2**: Killing a client under load can trigger an untrapped exception in the listener.

The following error can be triggered under certain circumstances when server under load and a client application(s) get killed. Note that in this test, the client application controlled 200 DR "Clients" for testing purposes and all 200 were aborted at the same time; however there is no reason why it could not happen with fewer client(s) being terminated.

System.NullReferenceException: Object reference not set to an instance of an object.
      at DarkRift.BigEndianHelper.ReadInt32(Byte[] source, Int32 offset)
      at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.ProcessHeader(SocketAsyncEventArgs args)
      at DarkRift.Server.Plugins.Listeners.Bichannel.BichannelServerConnection.ReceiveHeaderAndBody(SocketAsyncEventArgs args)

Caused by there being no bytes in "source". Fix is to validate the buffer has contents before sending through to be counted.

Notes:
 - tested in our test setup; 1000 clients died without killing server; (a parallel bug in our test clients was thrown and crashed the test clients as expected - server processed and cleaned up appropriately and was ready for more connections.
 - received "[Warning] ObjectCacheMonitor    4494 AutoRecyclingArray objects were finalized last period." but no corresponding MessageBuffer message. This needs further investigating

**Comment by RobbieLePommie** [comment]
Pull request created with both fixes in.

**Comment by RobbieLePommie** [comment]
Issue 1: Testing for race conditions is tricky: It was fairly reliable bug when I had the client send a message immediately after the connect() but not guaranteed - this means you can only test code works, which you do anyway.

Issue 2: TL;DR; I think another race condition, so not reliably testable. I noted in Discord that others have encountered the issue on a hard disconnect, so may be reproduceable under controlled circumstances, but my analysis also suggested a race condition. (This is now from memory, and never 100% proven but the logic followed) You need to have data in an incoming Message or AutoRecylingArray in ObjectCache pool. Then simultaneously process the message at the same time as the client gets destroyed (and thus the Message and/or AutoRecylingArray gets destroyed [aka returned to the pool]). Unconfirmed if you also need the Message to have been grabbed from the pool by another client and the AutoRecylingArray not yet replaced. This potentially could be worrying if the AutoRecylingArray could be replaced while the Message is in flight as the buffer could belong to a different client. But I didn't get that far to assess.

Side note: the variable "currentlyLoungingInAPool" took me ages to understand that variable based on it's name; I read it totally the wrong way!

**Comment by JamJar00** [comment]
>Side note: the variable "currentlyLoungingInAPool" took me ages to understand that variable based on it's name; I read it totally the wrong way!

Younger me trying to be funny, sorry about that. I renamed this to be more sensible across the board in a branch I had for object caching improvements, once the Unordinal team have a bit more time I'll push to get that finished off and merged

**Comment by 4real** [comment]
Merged #163, let me know if not sufficient.
