### ISSUE TITLE
Build dependencies are in obsolescence

### ISSUE THREAD

**Issue by epicality85** [DarkRiftNetworking/DarkRift#153]
### Quick Description
Long list of build errors on a fresh install of VS2022CE and windows.

### Explanation
Loooooong lis of errors due to missing dependencies like net4.0:
<img width="1522" alt="Darkrift fail to build solution" src="https://user-images.githubusercontent.com/13194207/193368045-9271c59c-0231-4466-a847-671296aa2c0a.png">

#### For Issues
Any build on new installs, due to VS2022CE obsoleting most of the dependencies.

**Comment by JamJar00** [comment]
This feels more like an issue with the developer packs you have installed. DR targets a lot of different .NET versions and you probably need them all installed for VS to be happy. [This line](https://github.com/DarkRiftNetworking/DarkRift/blob/master/DarkRift.Server.Console/DarkRift.Server.Console.csproj#L6) shows all the frameworks you need available (or remove them from there and the other csproj if you don't want them I guess!)

Perhaps we need more clarification in the documentation for building from source?

**Comment by epicality85** [comment]
Too frustrating really. Can't find packages required in NuGet. Don't have time to build dependencies, to build dependencies, to build dependencies...
