### ISSUE TITLE
Clients unable to connect when server running on Azure Container Instances

### ISSUE THREAD

**Issue by kapitanmliko** [DarkRiftNetworking/DarkRift#171]
### Quick Description
Right now it's impossible to connect to a DarkRift server running on Azure Container Instances (ACI) because every UDP message smaller than 12 bytes is dropped and UDP connection "ack/hello" message is currently only 8 bytes.

### Explanation
While it's certainly problem on MSFT's side it's still affecting DarkRift's ability to be deployed on ACI.
It's crucial for my use-case to run servers on ACI as my entire infrastructure is running on Azure and is built around it.

I have investigated and came to a conclusion that all that needs to be done to make DarkRift on ACI possible is to change the size of the server-sent udp hello message.

#### Issue
- When the server is running on ACI, clients are unable to connect.
- To reproduce this issue we just need to run the server on ACI.

Kindly review and consider merging my incoming PR. Thank you.

**Comment by 4real** [comment]
#175 contains the final version.

**Comment by kapitanmliko** [comment]
Tested with build from master after #175 merge and issue is indeed resolved. Thank you for your fix 4real!
