### ISSUE TITLE
Cliend ID and Server ID mismatch

### ISSUE THREAD

**Issue by Mravara** [DarkRiftNetworking/DarkRift#51]
### Quick Description
Client IDs in some cases get mismatched.

### Explanation
I have two unity instances running, one for the Client and one for the Server. When I get e.Client.ID on the server the first time, it's 0 as it should be. So is on the client. However, if I disconnect the client and connect again, on client side the ID will again be 0 and on the server side it will be 1.

### To reproduce:
 - Send ClientID from the client to the server, Debug.Log it before sending.
 - Debug.Log it once again on server side upon receiving the message.
 - They should both be 0
 - Disconnect the client and connect again
 - Do the same thing with the logging
 - They are 0 and 1 now

Cheers

**Comment by Reousa** [comment]
This works fine on my side on version 2.2.0, it could be a coding issue. Can you perhaps give us some code snippets?

**Comment by Mravara** [comment]
Ok I went to check and I the client IDs work but those are not the right steps to take when reproducing. My mistake.

Do this:
 - Run two instances of Unity, one as the Server one as the Client
 - Connect client to the server and Debug.Log the client's ID on the client side. (UnityClient.ID)
 - When connected, logging the clients ID on the server is 0 as well as it's on the client.
 - But, if you disconnect and connect again on the client. The server will think he's ID is 1 but the clients ID is actually again 0 (UnityClient.ID)

**Comment by JamJar00** [comment]
I'm afraid I can't reproduce this @Mravara 🙁 

Are you sure that you're waiting for DarkRift to connect before outputting the ID on the client side? The default when it doesn't have an ID will be 0 so would explain what's happening.

**Comment by JamJar00** [comment]
Closing as I couldn't reproduce it and there's been no response from the OP since November! If you think it's still an issue feel free to repoen 🙂
