### ISSUE TITLE
Getting the ip/port server is currently open on in unity embedded server

### ISSUE THREAD

**Issue by adanub** [DarkRiftNetworking/DarkRift#52]
### Quick Description
Could you please add in the current ip/port the server is open on as readonly fields/properties in the unity embedded server script? Its been rather annoying to get it automatically since you switched over to the xml config based system and removed ip and port fields from the scripts.

**Comment by JamJar00** [comment]
As discussed on Discord, this isn't necessarily simple as the port and IP are only stored in the NetworkListener, so any solution would only work for a small set of network listeners. I'll think it over.

**Comment by JamJar00** [comment]
The IP and port the server is listening on are now exposed in the NetworkListener class so this should be significantly easier to access now.

You should be able to do:
```c#
NetworkListener listener = NetworkListenerManager.GetNetworkListenerByName("default");
IPAddress ipAddress = listener.Address;
ushort port = listener.Port;
```

Apologies for how hard the previous update made this, I hadn't realised I'd made them quite so inaccessible!

Feel free to reopen this for further discussion if you need to.

**Comment by Mr-Yesorno** [comment]
Hum no it doesn't work (anymore?):
IPAddress ipAddress = listener.Address; //(NetworkListener does not 
contain a definition for 'Address'...) nor 'Port',

Also, how do you get the IP address of a e.Client?

Btw I'm having a blast with DarkRift :)

**Comment by JamJar00** [comment]
Can you check which version you're on? The asset store still has 2.3.1 on as the 2.4.x branch was a little squiff! I think this check was introduced during 2.4.x so you might need [2.4.5](http://www.darkriftnetworking.com/DarkRift2/Releases/Free/2.4.5.unitypackage) instead.

Frankly I think I'll just put that version on the asset store now, it's more stable that 2.3.1 at this point!

**Comment by Mr-Yesorno** [comment]
I was using 2.3.1 Pro. (Finally found the version number: in the server logs).
Thanks for 2.4.5 it seems stable!

**Comment by Mr-Yesorno** [comment]
Found that you may get the server address and port from  ClientManager.Address and ClientManager.Port (and it works in 2.3.1).

To try 2.4.5 I mixed a lot of xml files and the result was that the unix servers
stopped to work... Many wonderful hours later in the magical world
of the programmer I tried the last combo possible, all the files straight from the 
window compilation up to the server, and nothing else like Net Core or whatnot's (lol).

I just say for those wondering what the zipped Net Core and Framework are for...
;) wink wink
