### ISSUE TITLE
_ in Plugin Name

### ISSUE THREAD

**Issue by omerfaruk** [DarkRiftNetworking/DarkRift#56]
### Quick Description
if i create plugin with _ it gives error.
### Explanation
When i create playermanager_ss  plugin for xmlunityserver it gives error.

**Comment by JamJar00** [comment]
I'm afraid I can't reproduce this! 😟 

This is the plugin I'm using, maybe you can supply a minimal example that does cause the error?
```csharp

using DarkRift.Server;
using System;

namespace UnderscoreTest
{
    public class Underscore_Test: Plugin
    {
        public Underscore_Test(PluginLoadData pluginLoadData) : base(pluginLoadData)
        {
        }

        public override bool ThreadSafe => true;

        public override Version Version => new Version(1, 0, 0);
    }
}
```

![image](https://user-images.githubusercontent.com/5931310/48301100-f390e780-e4df-11e8-8693-44efc3130c9a.png)

**Comment by JamJar00** [comment]
Closing as I couldn't reproduce it and there's been no response from the OP since November! If you think it's still an issue feel free to repoen 🙂
