### ISSUE TITLE
Unity freezes on reconnect on .NET 3.5

### ISSUE THREAD

**Issue by LestaAllmaron** [DarkRiftNetworking/DarkRift#57]
### Quick Description
Connecting from the unity editor to any Darkrift server only works for the first time if the scripting runtime version is set to 3.5 equivalent.

It seems like the issue is only present in the newest Darkrift version(2.3). 

### How to reproduce
- create a new project
- start a console server
- Add a UnityClient to the scene with default settings
- Press Play
- Stop Play
- Press Play again -> unity editor freezes

**Comment by JamJar00** [comment]
I'm afraid I can't reproduce this at the moment using Unity 2018.2.15f1.

Sending over a video so I can check I'm doing it correctly and the server log files would be very useful! 🙂

**Comment by LestaAllmaron** [comment]
I also can't reproduce it... But there were multiple people with that issue and changing to 4.x fixed it for them (search for 3.5 in the discord). Maybe it got fixed with 2.3.1 or maybe they just needed a re import( changing to 4,x does re import everything).

**Comment by JamJar00** [comment]
Closing as I haven't heard any recent problems related to this. If anyone thinks it's still an issue feel free to repoen 🙂
