### ISSUE TITLE
ClientManager.Port should be read from the socket

### ISSUE THREAD

**Issue by Aranir** [DarkRiftNetworking/DarkRift#66]
### Quick Description
`ClientManager.Port` returns the port as specified in the configuration, rather than the reading it from the socket

### Explanation
If in the configuration value of `0` for the port is specified, the server is started with a random available port (not actually 0). but the port reported by the `ClientManager.Port` is 0 (as specified) rather than the actual port which is currently used.

**Comment by JamJar00** [comment]
This is fixed in the next version!
