### ISSUE TITLE
`IClient.Disconnect()` throws a `System.Net.Sockets.SocketException`

### ISSUE THREAD

**Issue by Reousa** [DarkRiftNetworking/DarkRift#67]
### Quick Description
Calling `IClient.Disconnect()` causes the following exception:

`Client [0] disconnected: OperationAborted.  System.Net.Sockets.SocketException (0x80004005): The I/O operation has been aborted because of either a thread exit or an application request`

#### Setup
* Stand alone DR2 server.
* DR2 Plugin runs in default thread, with a child thread for the game engine simulation.
* `ThreadSafe => true`, but it also happens on `ThreadSafe => false`.

#### Steps to reproduce
```csharp
private void ClientConnected(object sender, ClientConnectedEventArgs e)
{
	e.Client.MessageReceived += MessageRecieved;
}

private void MessageRecieved(object sender, MessageReceivedEventArgs e)
{
	if (e.Tag == (ushort)Tags.AuthRequest)
	{
		AuthenticatePlayer(e);
	}
}

private void AuthenticatePlayer(MessageReceivedEventArgs e)
{
	//Do some validation
	if (condition)
	{
		//doStuff
	}
	else
	{
		e.Client.Disconnect();
	}
}
```

**Comment by JamJar00** [comment]
This appears to be harmless but probably slightly worrying for users. Probably due to the timing of the disconnect.

**Comment by ianrichman7** [comment]
Calling IClient.Disconnect() also invokes the OnClientDisconnect event twice. This can serve as a problem for plugins that attempt to wrap around the default network listener, or subscribe to that event in any other capacity. The first disconnection is clean, but the second one throws the socket error.

**Comment by JamJar00** [comment]
This should be fixed in the next version! :)
