### ISSUE TITLE
DarkRift doesn't properly dispose of clients on custom listener

### ISSUE THREAD

**Issue by Derek-R-S** [DarkRiftNetworking/DarkRift#68]
### Description
DarkRift will not properly dispose of clients on a custom listener unless there is a callback on 
```c#
Server.ClientManager.ClientDisconnected
```

### Workaround
To work around this issue, you can add a callback to "Server.ClientManager.ClientDisconnected" when you start your server.
Example workaround:
```c#
GetComponent<XmlUnityServer>().Server.ClientManager.ClientDisconnected += (s, c) => Debug.Log("Client Disconnected.");
```

**Comment by JamJar00** [comment]
This should be fixed in the next version! Thanks for spotting this!
