### ISSUE TITLE
MakePingAchnowledgementMessage

### ISSUE THREAD

**Issue by Toocanzs** [DarkRiftNetworking/DarkRift#69]
`message.MakePingAchnowledgementMessage()` should be spelled `message.MakePingAcknowledgementMessage()`

**Comment by JamJar00** [comment]
Fixed in the next version!

I've taken the decision to break backwards compatibility and straight up fix this rather than leave the typo in and create a correctly named method on the grounds that it's confusing and not that many people will be using this feature yet. Sorry if that affects you!
