### ISSUE TITLE
DarkRiftClient.Connect(NetworkClientConnection) freezes build/editor

### ISSUE THREAD

**Issue by Derek-R-S** [DarkRiftNetworking/DarkRift#76]
#### Description
If you use DarkRiftClient.Connect(NetworkClientConnection) it will freeze the editor/builld.

#### Repro.
Make a custom listener
Try to use DarkRiftClient.Connect(NetworkClientConnection).

#### Extra
I managed to fix this by decompiling and changing some code, but thats not ideal. Hope it gets patched soon.

**Comment by JamJar00** [comment]
Can you tell me what code you had to change? That would be a big help.

**Comment by Derek-R-S** [comment]
It being decompiled this could vary from the actual source, but it was these two lines:

setupMutex.Reset();
setupMutex.WaitOne();

**Comment by JamJar00** [comment]
That suggests to me that your custom listener wasn't able to send and a receive message.

As part of the connection process the DarkRift server sends an initial message to the client with an ID, the client hence waits for this ID when connecting. The client will wait for a maximum of 10 seconds for that ID so it shouldn't be locking you up.

**Comment by Derek-R-S** [comment]
Ok so im quessing that then this happened: my listener required unity update to be called for checking if theres a message and since it was frozen would never actually be able to recieve the message

**Comment by JamJar00** [comment]
That would likely make sense, though I'm not sure there's an easy way to fix such an issue from DarkRift. You've built yourself a deadlock, and I can only really see that being solvable if you explicitly run your recieve loop (that would normally be called from Update) in the Connect sequence for a bit to retrieve that first message.

The timeout was probably only added around 2.4.0, I don't know if you're currently running an older verion?

**Comment by Derek-R-S** [comment]
Yeah i was using 2.3.1

**Comment by Derek-R-S** [comment]
Ok thats good that its not a bug and just a flaw with my listener.
