### ISSUE TITLE
2.4.3 free version .mdb files error

### ISSUE THREAD

**Issue by LestaAllmaron** [DarkRiftNetworking/DarkRift#78]
The free version form the asset store shows these errors after importing:
![image](https://user-images.githubusercontent.com/43687322/57048925-5cc70b80-6c76-11e9-90d8-fb7e69d450f7.png)

**Comment by JamJar00** [comment]
I'm not actually sure where those files have come from. They're not generated as part of something I do so I presume Unity generated them and didn't keep them up to date. I've removed them from the next version and will keep this in mind.
