### ISSUE TITLE
DarkRiftClient holds on `Connecting` after failed connection attempt

### ISSUE THREAD

**Issue by Soren025** [DarkRiftNetworking/DarkRift#81]
### Quick Description
`DarkRiftClient` holds on the `Connecting` state after failing to connect to a server.

### Explanation
I have encountered a bug when the `DarkRiftClient` fails to connect to a server. What happens is that after failing to connect, something seems to lock up internally and the `ConnectionState` remains in the `Connecting` state. Furthermore, any interaction with the `DarkRiftClient` that involves network interaction will throw the following exception...

`SocketException: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.`

I have confirmed that the exception is thrown when calling `Connect()`, `Disconnect()`, or `Dispose()` once in the locked `Connecting` state.

I first encountered this issue within a custom Unity component interacting with `DarkRiftClient`, however I have replicated this issue with the provided `UnityClient` component.

1. Attach `UnityClient` to an object in your scene.
2. Write code to log the `ConnectionState` (I added it to the `UnityClient` `Update()` method)
3. Provide no server for the client to connect to.
4. Enable auto start and enter play mode
5. Observe the logs showing the `ConnectionState`.
6. Exit play mode, there will be the above mentioned exception as `OnApplicationQuit()` ends up calling `Dispose()` on the `DarkRiftClient`.

Here is a screenshot of my log doing the above steps, I entered and exited play mode really fast to keep the amount of `ConnectionState` logs to a minimum.

![Error Log](https://puu.sh/DAoRj/08ab2208cb.png)

This occurred for me on the latest version of DarkRift (at the time being 2.4.3) as well as a version provided by Allmaron (2.3.1) on discord to attempt to resolve the issue.

My unity version is 2019.1.1f1
Also tested on unity version 2018.3.14f1

**Comment by alexpdaniel** [comment]
Issue persists with 2.8. 

After manually calling 
`client.ConnectInBackground(serverAddress, serverPort, true, ConnectCompleteHandler);`

The ConnectCompleteHandler fires fine.

The connectionstate remains at "Connecting" even after the connection has failed and the handler has fired.

**Comment by JamJar00** [comment]
Fixed in next version. So sorry this took so long to get sorted!
