### ISSUE TITLE
Change the `SerializeEvent` family's access modifiers from `internal` to `public`

### ISSUE THREAD

**Issue by Reousa** [DarkRiftNetworking/DarkRift#83]
### Description
Change the `SerializeEvent` family's access modifiers from `internal` to `public`. 
This would allow for an easier time creating the events to mock or test without needing a real client & without breaking backwards compatibility.

Example:
The ability to do this outside of DarkRift DLLs
`DeserializeEvent Foo = new DeserializeEvent(params);`

**Comment by JamJar00** [comment]
This should be available next version!
