### ISSUE TITLE
Have `IDarkRiftSerializable`'s `Deserialize` return `IDarkRiftSerializable` instead of `void`

### ISSUE THREAD

**Issue by Reousa** [DarkRiftNetworking/DarkRift#84]
### Quick Description
Have `IDarkRiftSerializable`'s `Deserialize` return `IDarkRiftSerializable`.

### Explanation
Making `Deserialize` return a `IDarkRiftSerializable` will allow the use of lines such as:

`MyType Foo = new MyType().Deserialize(params) as MyType;`

instead of being forced to:
`MyType Foo = new MyType();`
`Foo.Deserialize(params);`

Just a minor quality of life improvement and it doesn't break backwards compatibility, combined with #83 it makes mocking & testing a lot more convenient.

This could also allow an easier implementation of `IDisposable` to messages that inherit from `IDarkRiftSerializable` and using a `using` clause on them.

**Comment by JamJar00** [comment]
While this doesn't break backwards compatibility in usage this would require a change to everything implementing `IDarkRiftSerializable` as the method signature changes, i.e.
```csharp
// This
public override void Deserialize(...)
// becomes
public override MyType Deserialize(...)
```
I'm also hesitant to do this as you should probably be doing `MyType foo = reader.ReadSerializable<MyType>()` or 
```
MyType foo = new MyType();
reader.ReadSerializable(foo)
```
Though the later case may be a good place to do this.

**Comment by Reousa** [comment]
Hah. I didn't realize you could do that actually.

Renders my suggestion obsolete, thanks for taking a look though! :)
