### ISSUE TITLE
Server Console Command List

### ISSUE THREAD

**Issue by Bamboy** [DarkRiftNetworking/DarkRift#85]
A default console command to list all commands. 
Perhaps "help" without any parameters.

**Comment by JamJar00** [comment]
Done in next version!

```
help -l
help -l=DemoCommand
```

**Comment by JamJar00** [comment]
![image](https://user-images.githubusercontent.com/5931310/61312677-d3dd5c00-a7f0-11e9-91e9-a929146ab03d.png)
