### ISSUE TITLE
Link.xml file missing from 2.3.1

### ISSUE THREAD

**Issue by MrBabadook** [DarkRiftNetworking/DarkRift#94]
The link.xml file containing the code:

```
<linker>
    <!-- Because DarkRift dynamically loads stuff Unity code strips it and breaks it in 2018.3 plus, tell it not to -->
    <assembly fullname="DarkRift" preserve="all"/>
    <assembly fullname="DarkRift.Server" preserve="all"/>
    <assembly fullname="DarkRift.Client" preserve="all"/>
</linker>
```

is missing from current downloads. Someone in the discord was nice enough to provide it, but it seems to be missing for others as well, even with pro.

**Comment by JamJar00** [comment]
Hey! Thanks for leaving the issue!

If I remember correctly the `link.xml` file was only added to the package in version 2.4.0. Sadly that's not the version on the asset store at the moment so you won't find it in that version! Can you check what version you've currently got?

If it's 2.4.0+ then this is definitely an issue!

Jamie

**Comment by MrBabadook** [comment]
It's an issue in version 2.3.1 (current asset store) - but that is the version most people are finding/using atm. It might be worth updating the store page to include it in the meantime. Is 2.4.0+ going back up soon?

**Comment by JamJar00** [comment]
2.4.5 is stable but we didn't upload it to the store as we wanted to wait until 2.5.0 and then start afresh, unfortunately 2.5.0 hasn't come out as quickly as we hoped!

I'm going to close this as it has actually been fixed, and I'll have another think about uploading 2.4.5 in the meantime!

Cheers for reporting the issue!
