### ISSUE TITLE
Unhandled exception when loading plugins leads to crash

### ISSUE THREAD

**Issue by Reousa** [DarkRiftNetworking/DarkRift#97]
### Quick Description
An unhandled null reference exception in `PluginFactory` causes the program to crash without logging properly.

### Explanation
In `PluginFactory` at line `155` in version `2.3.1`, and if a DLL being referenced by a plugin is missing, an unhandled `NullReferenceException` is thrown causing the program to terminate ungracefully due to the `Assembly.GetTypes()` call not being able to load the DLL & returning null values.

#### For Issues
- Steps to reproduce it
Reference an external DLL or Nuget package in a DR2 plugin, then remove the DLL from the build & run the server.

- Any other comments that might help us
Adding a warning for the user that a referenced assembly might be missing is a good quality of life improvement, as the issue can be rather hard to pin-point in larger projects.

A further improvement would be to [check ](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getreferencedassemblies?view=netstandard-2.0)if any references are actually missing on startup.

**Comment by Reousa** [comment]
For reference:
![Img](https://media.discordapp.net/attachments/360144883148652554/667581158552371241/dvR6vJwqkv.png?width=931&height=473)

**Comment by JamJar00** [comment]
Fixed in the next version!

It would be good if you can pull that further improvement out into a separate card as well!

Thanks
